apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-restful-sample
  labels:
    app: springboot-restful-sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-restful-sample
  template:
    metadata:
      labels:
        app: springboot-restful-sample
    spec:
      containers:
      - name: springboot-restful-sample
        image: aprabhat/springboot-restful-sample:v1.0
        ports:
        - containerPort: 8080