apiVersion: v1
kind: Service
metadata:
  name: springboot-restful-sample-service
spec:
  type: LoadBalancer
  selector:
    app: springboot-restful-sample
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080