apiVersion: v1
kind: Service
metadata:
  name: springboot-restful-sample-service
spec:
  selector:
    app: springboot-restful-sample
  ports:
  - protocol: TCP
    port: 8080
  type: NodePort
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-restful-sample
  labels:
    app: springboot-restful-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-restful-sample
  template:
    metadata:
      labels:
        app: springboot-restful-sample
    spec:
      containers:
      - name: springboot-restful-sample
        image: aprabhat/springboot-restful-sample:v1.0
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 0.5
            memory: 256Mi
        ports:
        - containerPort: 8080
        imagePullPolicy: Always